<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>XCleaner.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>XCleaner.App</StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Authors>Glitchspire</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="XCleaner.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="Velopack" Version="1.2.110-ge826545" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\wpfui-icon-256.png" />
    <None Remove="Assets\wpfui-icon-1024.png" />
    <None Remove="Assets\XCleaner-256.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\wpfui-icon-256.png" />
    <Resource Include="Assets\wpfui-icon-1024.png" />
    <Resource Include="Assets\XCleaner-256.png" />
    <None Remove="Assets\folder-256.png" />
    <Resource Include="Assets\folder-256.png" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

</Project>
